/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class NewJFrame extends javax.swing.JFrame {
    boolean respuestaMysql;
    boolean respuestaSqlserver;
            
    ConexMysql conexion_from_probar_mysql;
    ConexServer conexion_from_probar_sqlserver;
    
    ConexMysql conexion2_from_probar_mysql; // conexion a bitacora de replicacion
    
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdialog_botonConfiguracion = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textField_nombreInstancia_mysql = new javax.swing.JTextField();
        textField_nombreBD_mysql = new javax.swing.JTextField();
        textField_puerto_mysql = new javax.swing.JTextField();
        textField_nombreUsuario_mysql = new javax.swing.JTextField();
        textField_password_mysql = new javax.swing.JTextField();
        boton_probarMysql = new javax.swing.JButton();
        textField_mostrarMnsj_afterTest_mysql = new javax.swing.JLabel();
        boton_recent_mysql = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textField_nombreInstancia_sqlserver = new javax.swing.JTextField();
        textField_nombreBD_sqlserver = new javax.swing.JTextField();
        textField_puerto_sqlserver = new javax.swing.JTextField();
        textField_nombreUsuario_sqlserver = new javax.swing.JTextField();
        textField_password_sqlserver = new javax.swing.JTextField();
        boton_probarSqlServer = new javax.swing.JButton();
        textField_mostrarMnsj_afterTest_sqlserver = new javax.swing.JLabel();
        boton_recent_sqlserver = new javax.swing.JButton();
        jdialog_botonReplicar = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        mysqlShowTables = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        sqlserverShowTables = new javax.swing.JTable();
        boton_mover_a_tabla_sqlserver = new java.awt.Button();
        boton_quitar_de_sqlserver = new java.awt.Button();
        boton_job = new javax.swing.JButton();
        label_informacion_job = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        botonConfiguracion = new javax.swing.JButton();
        botonReplicar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jdialog_botonConfiguracion.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jdialog_botonConfiguracionComponentHidden(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("base de datos origen");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("nombre de instancia");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("nombre base da datos");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("puerto");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("nombre usuario");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("password");

        boton_probarMysql.setText("probar");
        boton_probarMysql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_probarMysqlActionPerformed(evt);
            }
        });

        boton_recent_mysql.setText("recent");
        boton_recent_mysql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_recent_mysqlActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(boton_recent_mysql, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boton_probarMysql)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textField_nombreUsuario_mysql, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(textField_puerto_mysql)
                            .addComponent(textField_nombreInstancia_mysql)
                            .addComponent(textField_nombreBD_mysql)
                            .addComponent(textField_mostrarMnsj_afterTest_mysql, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField_password_mysql)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textField_nombreInstancia_mysql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(textField_nombreBD_mysql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(textField_puerto_mysql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(textField_nombreUsuario_mysql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(textField_password_mysql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boton_probarMysql, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton_recent_mysql))
                    .addComponent(textField_mostrarMnsj_afterTest_mysql, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("base de datos destino");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("nombre de instancia");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("nombre base da datos");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("puerto");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("nombre usuario");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("password");

        boton_probarSqlServer.setText("probar");
        boton_probarSqlServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_probarSqlServerActionPerformed(evt);
            }
        });

        boton_recent_sqlserver.setText("recent");
        boton_recent_sqlserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_recent_sqlserverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(boton_recent_sqlserver, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boton_probarSqlServer)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textField_password_sqlserver, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(textField_nombreUsuario_sqlserver)
                            .addComponent(textField_puerto_sqlserver)
                            .addComponent(textField_nombreInstancia_sqlserver)
                            .addComponent(textField_nombreBD_sqlserver)
                            .addComponent(textField_mostrarMnsj_afterTest_sqlserver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textField_nombreInstancia_sqlserver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textField_nombreBD_sqlserver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textField_puerto_sqlserver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(textField_nombreUsuario_sqlserver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(textField_password_sqlserver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boton_probarSqlServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton_recent_sqlserver))
                    .addComponent(textField_mostrarMnsj_afterTest_sqlserver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout jdialog_botonConfiguracionLayout = new javax.swing.GroupLayout(jdialog_botonConfiguracion.getContentPane());
        jdialog_botonConfiguracion.getContentPane().setLayout(jdialog_botonConfiguracionLayout);
        jdialog_botonConfiguracionLayout.setHorizontalGroup(
            jdialog_botonConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdialog_botonConfiguracionLayout.setVerticalGroup(
            jdialog_botonConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdialog_botonConfiguracionLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdialog_botonReplicar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jdialog_botonReplicarComponentHidden(evt);
            }
        });

        mysqlShowTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "mysql tables"
            }
        ));
        jScrollPane1.setViewportView(mysqlShowTables);

        sqlserverShowTables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "sqlserver tables"
            }
        ));
        jScrollPane2.setViewportView(sqlserverShowTables);

        boton_mover_a_tabla_sqlserver.setLabel(">>");
        boton_mover_a_tabla_sqlserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_mover_a_tabla_sqlserverActionPerformed(evt);
            }
        });

        boton_quitar_de_sqlserver.setLabel("<<");
        boton_quitar_de_sqlserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_quitar_de_sqlserverActionPerformed(evt);
            }
        });

        boton_job.setText("job");
        boton_job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_jobActionPerformed(evt);
            }
        });

        label_informacion_job.setText("last job: ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel14.setText("sin replicar");

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel15.setText("replicando");

        javax.swing.GroupLayout jdialog_botonReplicarLayout = new javax.swing.GroupLayout(jdialog_botonReplicar.getContentPane());
        jdialog_botonReplicar.getContentPane().setLayout(jdialog_botonReplicarLayout);
        jdialog_botonReplicarLayout.setHorizontalGroup(
            jdialog_botonReplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdialog_botonReplicarLayout.createSequentialGroup()
                .addGroup(jdialog_botonReplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdialog_botonReplicarLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(boton_job))
                    .addGroup(jdialog_botonReplicarLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(label_informacion_job, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jdialog_botonReplicarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jdialog_botonReplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdialog_botonReplicarLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(jdialog_botonReplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boton_quitar_de_sqlserver, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(boton_mover_a_tabla_sqlserver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jdialog_botonReplicarLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jdialog_botonReplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdialog_botonReplicarLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGap(37, 37, 37))
        );
        jdialog_botonReplicarLayout.setVerticalGroup(
            jdialog_botonReplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdialog_botonReplicarLayout.createSequentialGroup()
                .addGroup(jdialog_botonReplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdialog_botonReplicarLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jdialog_botonReplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(32, 32, 32)
                        .addGroup(jdialog_botonReplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jdialog_botonReplicarLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(boton_mover_a_tabla_sqlserver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(boton_quitar_de_sqlserver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(boton_job)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_informacion_job, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        boton_mover_a_tabla_sqlserver.getAccessibleContext().setAccessibleName("");

        jdialog_botonReplicar.getAccessibleContext().setAccessibleName(">>");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonConfiguracion.setText("configuracion");
        botonConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfiguracionActionPerformed(evt);
            }
        });

        botonReplicar.setText("replicar");
        botonReplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReplicarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel1.setText("MYSQL- SQL SERVER INTEGRATOR ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(botonReplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(botonConfiguracion)
                .addGap(87, 87, 87)
                .addComponent(botonReplicar)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfiguracionActionPerformed
        // TODO add your handling code here:
        
        //el clic hace que se despliegue el menu de las conexiones entre ambas bases de datos
        jdialog_botonConfiguracion.setVisible(true);
        jdialog_botonConfiguracion.pack();
        jdialog_botonConfiguracion.setLocationRelativeTo(this);
        
        //hide frame
        this.setVisible(false);
        
    }//GEN-LAST:event_botonConfiguracionActionPerformed

    private void boton_probarMysqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_probarMysqlActionPerformed
        // TODO add your handling code here:
        String nombreInstancia=textField_nombreInstancia_mysql.getText();
        String nombreBD=textField_nombreBD_mysql.getText();
        String puerto=textField_puerto_mysql.getText();
        String nombreUsuario=textField_nombreUsuario_mysql.getText();
        String password=textField_password_mysql.getText();
        
        //quitando espacios que producen fallos
        nombreInstancia=nombreInstancia.trim();
        nombreBD=nombreBD.trim();
        puerto=puerto.trim();
        nombreUsuario=nombreUsuario.trim();
        password=password.trim();
        
        conexion_from_probar_mysql = new ConexMysql(nombreInstancia, nombreBD, puerto, nombreUsuario, password);
        
        respuestaMysql=conexion_from_probar_mysql.probarConexion();
        
        if (respuestaMysql) {
            //actualizar el jtextfield
            textField_mostrarMnsj_afterTest_mysql.setText("success on connection");
            
            try {
                //guardar una nueva conexion
                PreparedStatement ps = conexion_from_probar_mysql.con.prepareStatement("insert into "
                        + "CONNECTIONS_BIT (nombre_instancia,nombre_bd, puerto,user,password)  "
                        + "values('"+nombreInstancia+"','"+nombreBD+"','"+puerto+"','"+nombreUsuario+"','"+password+"');");
                
                ps.executeUpdate("insert into "
                        + "CONNECTIONS_BIT (nombre_instancia,nombre_bd, puerto,user,password)  "
                        + "values('"+nombreInstancia+"','"+nombreBD+"','"+puerto+"','"+nombreUsuario+"','"+password+"');");
                
                
                        
            } catch (SQLException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
            
        }else{
            //actualizar el jtextfield
            textField_mostrarMnsj_afterTest_mysql.setText("connection failed");
        }
         
    }//GEN-LAST:event_boton_probarMysqlActionPerformed

    private void boton_probarSqlServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_probarSqlServerActionPerformed
        // TODO add your handling code here:
        String nombreInstancia=textField_nombreInstancia_sqlserver.getText();
        String nombreBD=textField_nombreBD_sqlserver.getText();
        String puerto=textField_puerto_sqlserver.getText();
        String nombreUsuario=textField_nombreUsuario_sqlserver.getText();
        String password=textField_password_sqlserver.getText();
        
        //quitando espacios que producen fallos
        nombreInstancia=nombreInstancia.trim();
        nombreBD=nombreBD.trim();
        puerto=puerto.trim();
        nombreUsuario=nombreUsuario.trim();
        password=password.trim();
        
               
        conexion_from_probar_sqlserver = new ConexServer(nombreInstancia, nombreBD, puerto, nombreUsuario, password);
        
        respuestaSqlserver=conexion_from_probar_sqlserver.probarConexion();
        
        if (respuestaSqlserver) {
            //actualizar el jtextfield
            textField_mostrarMnsj_afterTest_sqlserver.setText("success on connection");
            
            
            try {
                //guardar una nueva conexion sqlserver
                
                PreparedStatement ps = conexion_from_probar_mysql.con.prepareStatement("insert into "
                        + "CONNECTIONS_SQLSERVER_BIT (nombre_instancia,nombre_bd, puerto,user,password)  "
                        + "values('"+nombreInstancia+"','"+nombreBD+"','"+puerto+"','"+nombreUsuario+"','"+password+"');");
                
                ps.executeUpdate("insert into "
                        + "CONNECTIONS_SQLSERVER_BIT (nombre_instancia,nombre_bd, puerto,user,password)  "
                        + "values('"+nombreInstancia+"','"+nombreBD+"','"+puerto+"','"+nombreUsuario+"','"+password+"');");
                
                
                        
            } catch (SQLException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
            
            
        }else{
            //actualizar el jtextfield
            textField_mostrarMnsj_afterTest_sqlserver.setText("connection failed");
        }
    }//GEN-LAST:event_boton_probarSqlServerActionPerformed

    private void botonReplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReplicarActionPerformed
        //cargar el dialog 
        jdialog_botonReplicar.setVisible(true);
        jdialog_botonReplicar.pack();
        jdialog_botonReplicar.setLocationRelativeTo(this);
        
        //ocultar opciones del frame
        this.setVisible(false);
     
        
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"Mysql tables"});
        
        //para sqlserver 
        DefaultTableModel modelo2 = new DefaultTableModel();
        modelo2.setColumnIdentifiers(new Object[]{"sqlserver tables"});
        
        
        //actualizar informacion del job
        //paste
        PreparedStatement psJob;
        try {
            psJob = conexion_from_probar_mysql.con.prepareStatement("select max(fecha) fechaMaxima from JOB_BIT");
            ResultSet rsJob = psJob.executeQuery("select max(fecha) fechaMaxima from JOB_BIT");

            //obtener el log mas reciente
            String lastFecha = null ;
            while (rsJob.next()) {
                lastFecha= rsJob.getString("fechaMaxima");
            }
            
            
                
            
            if (lastFecha==null) {
                //no records
                //actualizar jobLabel con no records
                label_informacion_job.setText("last job: no records");
            }else{
                //actualizar jobLabel con ultimo log
                label_informacion_job.setText("last job: "+lastFecha);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                
        
        
        try {
            
                       
            //listado de las tablas
            //show full tables from projectmysql
            PreparedStatement ps = conexion_from_probar_mysql.con.prepareStatement("show tables from projectmysql like '_NB' ");
            ResultSet rs=ps.executeQuery("show tables from projectmysql like '%_NB'");
            
            while (rs.next()) {
                modelo.addRow(new Object[]{rs.getString("Tables_in_projectmysql (%_NB)")});
            }
            mysqlShowTables.setModel(modelo);
            
            } catch (SQLException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            
        
    }//GEN-LAST:event_botonReplicarActionPerformed

    private void boton_mover_a_tabla_sqlserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_mover_a_tabla_sqlserverActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo= (DefaultTableModel)mysqlShowTables.getModel();
        int posRow = mysqlShowTables.getSelectedRow();
        int posColumn =mysqlShowTables.getSelectedColumn();
        
        Object valueFromMysql=modelo.getValueAt(posRow, posColumn);
        
        //para actualizar modelo en jtable sqlserver
        DefaultTableModel modelo2= (DefaultTableModel)sqlserverShowTables.getModel();
        modelo2.addRow(new Object[]{valueFromMysql.toString()});
        sqlserverShowTables.setModel(modelo2);
        
        modelo.removeRow(posRow);
        
               
                
    }//GEN-LAST:event_boton_mover_a_tabla_sqlserverActionPerformed

    private void boton_recent_mysqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_recent_mysqlActionPerformed
        // TODO add your handling code here:
        textField_nombreInstancia_mysql.setText("msqldb.cdvj4u1rep19.us-east-1.rds.amazonaws.com");
        textField_nombreBD_mysql.setText("projectmysql");
        textField_puerto_mysql.setText("3306");
        textField_nombreUsuario_mysql.setText("admin");
        textField_password_mysql.setText("adminmsql");
    }//GEN-LAST:event_boton_recent_mysqlActionPerformed

    private void boton_quitar_de_sqlserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_quitar_de_sqlserverActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo= (DefaultTableModel)sqlserverShowTables.getModel();
        int posRow = sqlserverShowTables.getSelectedRow();
        int posColumn =sqlserverShowTables.getSelectedColumn();
        
        Object valueFromMysql=modelo.getValueAt(posRow, posColumn);
        
        //para actualizar modelo en jtable sqlserver
        DefaultTableModel modelo2= (DefaultTableModel)mysqlShowTables.getModel();
        modelo2.addRow(new Object[]{valueFromMysql.toString()});
        mysqlShowTables.setModel(modelo2);
        
        modelo.removeRow(posRow);
        
        
    }//GEN-LAST:event_boton_quitar_de_sqlserverActionPerformed

    private void jdialog_botonReplicarComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jdialog_botonReplicarComponentHidden
        // TODO add your handling code here:
        
        //clean sqlserver table
        DefaultTableModel modelo3= (DefaultTableModel)sqlserverShowTables.getModel();
        modelo3.setRowCount(0);
        
        //pop up frame 
        this.setVisible(true);
        
    }//GEN-LAST:event_jdialog_botonReplicarComponentHidden

    private void boton_jobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_jobActionPerformed
        
        //confirmar
        int showConfirmDialog = JOptionPane.showConfirmDialog(null, "realmente quiere ejecutar el job?");
        
        if (showConfirmDialog==0) {//el usuario acepto
            
        
        
            for (int i = 0; i < sqlserverShowTables.getRowCount(); i++) {// todas las tablas para replicar

                String current= sqlserverShowTables.getValueAt(i, 0).toString();
                int index_of_=current.indexOf("_");
                current=current.substring(0,index_of_);//obtenemos el identificador general de la tabla POR EJM: CLIENTES_BIT , CLIENTES_NB OBTENEMOS CLIENTES 


                try {
                    // TODO add your handling code here:
                    //solicitar el ultimo log


                    //requerir conexiones
                    PreparedStatement psJob = conexion_from_probar_mysql.con.prepareStatement("select max(fecha) fechaMaxima from JOB_BIT where tabla ='"+current+"'");
                    ResultSet rsJob = psJob.executeQuery("select max(fecha) fechaMaxima from JOB_BIT where tabla ='"+current+"'");

                    //obtener el log mas reciente
                    //obtener el log mas reciente
                    String lastFecha = null;
                    while (rsJob.next()) {
                        lastFecha= rsJob.getString("fechaMaxima");
                    }


                    PreparedStatement pss;
                    ResultSet rss;
                    if (lastFecha==null) {
                        //ejecutar replicacion desde cero
                        pss = conexion_from_probar_mysql.con.prepareStatement("select * from "+current+"_BIT");
                        rss = pss.executeQuery("select * from "+current+"_BIT");
                    }else{
                        //ejecutar replicacion desde un punto de control

                        pss = conexion_from_probar_mysql.con.prepareStatement("select * from "+current+"_BIT "+" where fecha > '"+lastFecha+"'");//solo queremos actualizar datos desde la ultima replicacion
                        rss = pss.executeQuery("select * from "+current+"_BIT "+" where fecha > '"+lastFecha+"'");

                    }




                    while (rss.next()) {

                        String accion = rss.getString("accion");

                        if (accion.equals("insert")) {
                            //conexion con sql server
                            String id=rss.getString("nuevo_id");
                            String nombre=rss.getString("nuevo_nombre");
                            Statement ps2 = conexion_from_probar_sqlserver.conServer.createStatement();

                            ps2.executeUpdate("insert into "+current+"_NB (id,nombre) "
                                    + "values ("+id+",'"+nombre+"');");



                        }else if (accion.equals("update")){
                            String id =rss.getString("nuevo_id");
                            String nombre=rss.getString("nuevo_nombre");
                            Statement ps2 = conexion_from_probar_sqlserver.conServer.createStatement();

                            //update element
                            ps2.executeUpdate("update "+current+"_NB set nombre='"+nombre+"'"+" where id="+id);

                        }else{
                            String id =rss.getString("nuevo_id");
                            Statement ps2 = conexion_from_probar_sqlserver.conServer.createStatement();
                            //delete element
                            ps2.executeUpdate("delete from "+current+"_NB where id="+id);

                        }


                    }
                    //el job se hizo correctamente
                    pss = conexion_from_probar_mysql.con.prepareStatement("insert into JOB_BIT (tabla)values('"+current+"')");
                    pss.executeUpdate("insert into JOB_BIT (tabla)values('"+current+"')");
                    label_informacion_job.setText("job Executed!");

                } catch (SQLException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }


            
            
        }
            
            
    }else{
            JOptionPane.showMessageDialog(null, "operacion cancelada!");
        
    }        
        /*
        for (int i = 0; i < sqlserverShowTables.getRowCount(); i++) {
            
            Object valueAt = sqlserverShowTables.getValueAt(i, 0);
            
            if(valueAt.toString().equals("CLIENTES_NB")){
                
            }else{
                System.out.println("some error here");
            }
            
            
        }*/
        
    }//GEN-LAST:event_boton_jobActionPerformed

    private void boton_recent_sqlserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_recent_sqlserverActionPerformed
        // TODO add your handling code here:
        
        textField_nombreInstancia_sqlserver.setText("sqlserverdb.cdvj4u1rep19.us-east-1.rds.amazonaws.com");
        textField_nombreBD_sqlserver.setText("projectmysql");
        textField_puerto_sqlserver.setText("1433");
        textField_nombreUsuario_sqlserver.setText("admin");
        textField_password_sqlserver.setText("adminsqlserver");
    }//GEN-LAST:event_boton_recent_sqlserverActionPerformed

    private void jdialog_botonConfiguracionComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jdialog_botonConfiguracionComponentHidden
        // TODO add your handling code here:
        
        //pop up frame
        this.setVisible(true);
    }//GEN-LAST:event_jdialog_botonConfiguracionComponentHidden
    
       
        
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConfiguracion;
    private javax.swing.JButton botonReplicar;
    private javax.swing.JButton boton_job;
    private java.awt.Button boton_mover_a_tabla_sqlserver;
    private javax.swing.JButton boton_probarMysql;
    private javax.swing.JButton boton_probarSqlServer;
    private java.awt.Button boton_quitar_de_sqlserver;
    private javax.swing.JButton boton_recent_mysql;
    private javax.swing.JButton boton_recent_sqlserver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jdialog_botonConfiguracion;
    private javax.swing.JDialog jdialog_botonReplicar;
    private javax.swing.JLabel label_informacion_job;
    private javax.swing.JTable mysqlShowTables;
    private javax.swing.JTable sqlserverShowTables;
    private javax.swing.JLabel textField_mostrarMnsj_afterTest_mysql;
    private javax.swing.JLabel textField_mostrarMnsj_afterTest_sqlserver;
    private javax.swing.JTextField textField_nombreBD_mysql;
    private javax.swing.JTextField textField_nombreBD_sqlserver;
    private javax.swing.JTextField textField_nombreInstancia_mysql;
    private javax.swing.JTextField textField_nombreInstancia_sqlserver;
    private javax.swing.JTextField textField_nombreUsuario_mysql;
    private javax.swing.JTextField textField_nombreUsuario_sqlserver;
    private javax.swing.JTextField textField_password_mysql;
    private javax.swing.JTextField textField_password_sqlserver;
    private javax.swing.JTextField textField_puerto_mysql;
    private javax.swing.JTextField textField_puerto_sqlserver;
    // End of variables declaration//GEN-END:variables
}
